FROM ubuntu:latest

RUN apt-get update && apt-get install -y wget

RUN curl -L https://install.pivpn.io | bash
RUN wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip &&\
	unzip ngrok-stable-linux-arm.zip
RUN ./ngrok --version
RUN ./ngrok tcp 443
